import React from "react";
import {
  Trophy,
  Medal,
  Gamepad2,
  Target,
  Flame,
  Gem,
  Lightbulb,
  Rocket,
  Star,
  Sparkles,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Crown,
  Award,
  BarChart3,
  TrendingUp,
  TrendingDown,
  Timer,
  User,
  Users,
  ClipboardList,
  FileText,
  RefreshCw,
  Settings,
  Trash2,
  Search,
  Palette,
  Hourglass,
  Shield,
  Wrench,
  Coins,
  Scroll,
  Puzzle,
  Monitor,
  Volume2,
  VolumeX,
  Home,
  AlertOctagon,
  Film,
  Eraser,
  Dice5,
  Music,
  Zap,
  ImageIcon,
  Save,
  Pin,
  Play,
  Circle,
  Check,
  Bot,
  Bug,
  Camera,
  Plus,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  trophy: Trophy,
  medal: Medal,
  gamepad2: Gamepad2,
  target: Target,
  flame: Flame,
  gem: Gem,
  lightbulb: Lightbulb,
  rocket: Rocket,
  star: Star,
  sparkles: Sparkles,
  "check-circle-2": CheckCircle2,
  "x-circle": XCircle,
  "alert-triangle": AlertTriangle,
  crown: Crown,
  award: Award,
  "bar-chart-3": BarChart3,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  timer: Timer,
  user: User,
  users: Users,
  "clipboard-list": ClipboardList,
  "file-text": FileText,
  "refresh-cw": RefreshCw,
  settings: Settings,
  "trash-2": Trash2,
  search: Search,
  palette: Palette,
  hourglass: Hourglass,
  shield: Shield,
  wrench: Wrench,
  coins: Coins,
  scroll: Scroll,
  puzzle: Puzzle,
  monitor: Monitor,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  home: Home,
  "alert-octagon": AlertOctagon,
  film: Film,
  eraser: Eraser,
  dice5: Dice5,
  music: Music,
  zap: Zap,
  image: ImageIcon,
  save: Save,
  pin: Pin,
  play: Play,
  circle: Circle,
  check: Check,
  bot: Bot,
  bug: Bug,
  camera: Camera,
  plus: Plus,
};

export function renderIcon(name: string, className?: string) {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon className={className || "w-4 h-4 inline"} />;
}

export function getIconComponent(name: string): LucideIcon | null {
  return iconMap[name] || null;
}

export const ICON_NAMES = Object.keys(iconMap);

export default iconMap;
