// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = (
  (import.meta.env as any).VITE_SUPABASE_ANON_KEY ||
  (import.meta.env as any).VITE_SUPABASE_PUBLISHABLE_KEY
) as string | undefined;

// Check for missing env vars and provide helpful guidance
const missingUrl = !SUPABASE_URL;
const missingKey = !SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Allow runtime switching between persistent and non-persistent auth storage.
// When `remember me` is disabled, we store Supabase auth in sessionStorage.
// Otherwise, we default to localStorage for long-lived sessions.
const REMEMBER_ME_KEY = "auth_remember_me";

const dynamicStorage = {
  getItem(key: string) {
    try {
      const remember = localStorage.getItem(REMEMBER_ME_KEY) !== 'false';
      const storage = remember ? localStorage : sessionStorage;

      // Try primary storage first
      let value = storage.getItem(key);

      // If not found and we're looking for auth tokens, check the other storage
      // This helps with session recovery when users change devices/browsers
      if (!value && key.startsWith('sb-')) {
        const fallbackStorage = remember ? sessionStorage : localStorage;
        value = fallbackStorage.getItem(key);

        // If found in fallback, migrate it to correct storage
        if (value) {
          storage.setItem(key, value);
          fallbackStorage.removeItem(key);
        }
      }

      return value;
    } catch {
      return null;
    }
  },
  setItem(key: string, value: string) {
    try {
      const remember = localStorage.getItem(REMEMBER_ME_KEY) !== 'false';
      const storage = remember ? localStorage : sessionStorage;

      // Set in primary storage
      storage.setItem(key, value);

      // For auth tokens, also clean up from the opposite storage to prevent conflicts
      if (key.startsWith('sb-')) {
        const oppositeStorage = remember ? sessionStorage : localStorage;
        oppositeStorage.removeItem(key);
      }
    } catch {
      // ignore write errors
    }
  },
  removeItem(key: string) {
    try {
      // Remove from both to avoid leftovers when toggling
      localStorage.removeItem(key);
      sessionStorage.removeItem(key);
    } catch {
      // ignore
    }
  }
} as Storage;

export function setRememberMe(remember: boolean) {
  try {
    localStorage.setItem(REMEMBER_ME_KEY, remember ? 'true' : 'false');
    // When changing preference, clear existing tokens from the opposite storage
    // Supabase keys are prefixed with 'sb-' by default
    const clearOpposite = (storage: Storage) => {
      const keys: string[] = [];
      for (let i = 0; i < storage.length; i++) {
        const k = storage.key(i);
        if (k && k.startsWith('sb-')) keys.push(k);
      }
      keys.forEach(k => storage.removeItem(k));
    };
    if (remember) {
      clearOpposite(sessionStorage);
    } else {
      clearOpposite(localStorage);
    }
  } catch {
    // ignore
  }
}

// Create mock client for missing env vars or real client
const mockClient = {
  auth: {
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    signUp: () => Promise.resolve({ data: null, error: { message: "Supabase not configured. Please add environment variables." } }),
    signInWithPassword: () => Promise.resolve({ data: null, error: { message: "Supabase not configured. Please add environment variables." } }),
    signOut: () => Promise.resolve({ error: null })
  },
  from: () => ({
    select: () => Promise.resolve({ data: [], error: { message: "Supabase not configured. Please add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY environment variables." } }),
    insert: () => Promise.resolve({ data: null, error: { message: "Supabase not configured. Please add environment variables." } }),
    update: () => Promise.resolve({ data: null, error: { message: "Supabase not configured. Please add environment variables." } }),
    delete: () => Promise.resolve({ data: null, error: { message: "Supabase not configured. Please add environment variables." } })
  })
};

export const supabase = (missingUrl || missingKey)
  ? mockClient as any
  : createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: dynamicStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        // Improve session recovery with longer grace period
        refreshThreshold: 60, // Refresh tokens 60 seconds before expiry
      }
    });

if (missingUrl || missingKey) {
  console.error("[supabase] Missing environment variables. Please configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your deployment environment.");
}